[build]
  command = "make netlify"
  publish = "dashboard"
  functions = "functions"
[build.environment]
  GOBIN = "/opt/build/repo/functions"
[template.environment]
  GO_IMPORT_PATH = "GO_IMPORT_PATH. Set your repository location: github.com/[Account]/[Repository name]"
